const ku = {
  mainMenu: {
    home: 'سەرەکی',
    projects: 'پرۆژەکان',
    team: 'تیم',
    news: 'هەواڵەکان',
    careers: 'پیشەکان',
    services: 'خزمەتگوزارییەکان',
    partners: 'هاوبەشەکان',
    about: 'دەربارەی ئێمە',
    history: 'مێژووی کۆمپانیا',
    inHouse: 'ناوخۆیی',
    privacy: 'سیاسەتی نهێنی',
    terms: 'مەرج و یاساکان',
    contact: 'پەیوەندی',
  },
  welcome: 'Welcome to AlBina',
  description:
    'AlBina is a powerful and user-friendly accounting software designed to simplify your financial management. With AlBina, you can easily track your income and expenses, generate invoices, manage your accounts, and gain valuable insights into your financial health. Whether you are a small business owner, freelancer, or an individual looking to stay organized, AlBina has got you covered. Experience the convenience and efficiency of AlBina today and take control of your finances like never before.',
  errors: {
    '401': 'Authentication Error - Please login again',
    '403': 'You do not have access to this section',
    '404': 'Page or resource not found',
    '500': 'Server Error - Please try again later',
    network: 'Network Error - Please check your internet connection',
    unknown: 'An unknown error occurred',
    default: 'Error',
    loadingData: 'Error loading data',
  },
  MSG: {
    FILE_EXISTS_BY_SAME_NAME: 'A file with this name has already been registered.',
    TOO_MANY_REQUEST: 'Request limit exists.',
    EXISTS_IN_CART: 'This file is being used in the order cart.',
    EXISTS_IN_PreOrder: 'This file is being used in pre-order.',
    NOT_FOUND: 'Item not found',
    INVALID_REQUEST: 'Invalid request',
    UNAUTHORIZED: 'You do not have permission to access this section',
    SERVER_ERROR: 'Server error occurred',
    VALIDATION_ERROR: 'Data validation error',
    DUPLICATE_ENTRY: 'This item has already been registered',
    INSUFFICIENT_BALANCE: 'Insufficient account balance',
    EXPIRED_TOKEN: 'Token has expired',
    INVALID_CREDENTIALS: 'Username or password is incorrect',
    FORBIDDEN: 'Unauthorized access',
    BAD_REQUEST: 'Invalid request',
    TIMEOUT: 'Request timeout',
    NETWORK_ERROR: 'Network error',
    LOGIN_SUCCESSFULL: 'Login successful',
    SUCCESSED: 'Operation successful',
    SUCCESS: 'Operation successful',
    FAILED: 'Operation failed',
    OPERATION_FAILED_RETRY: 'Operation failed.',
    INVALID_TOKEN: 'Tracking code is invalid.',
    INVALID_COLOR_MODE: 'Color mode is invalid.',
    INVALID_DPI: 'DPI is invalid.',
    INVALID_RESOLUTION_UNIT: 'Resolution unit must be pixels/inch.',
    NOT_MATCH_WITH_OTHER: 'Selected file does not match other files.',
    SELECTED_FILE_NOT_EXISTS: 'Selected file does not exist.',
    PREORDER_NOT_FOUND: 'Pre-order not found.',
    INVALID_DATA: 'Data is invalid.',
    CUSTOMER_IS_EXSITS_BY_THIS_IDENTITIFIER: 'Customer with these details has already registered.',
    INVALID_IDENTITFIER: 'Entered identifier is invalid.',
    DATA_NOT_FOUND: 'Data not found.',
    INCORRECT_PASSWORD: 'Password is incorrect.',
    OTP_SENT: 'One-time password sent.',
    FAILED_OTP_SENT: 'Problem occurred in sending one-time password, please try again.',
    USER_NOT_FOUND: 'User information not found.',
    FOUNDED: 'Information found.',
    FULLY_PAY_FROM_BALANCE: 'Payment from wallet',
    FULLY_PAY_FROM_CREDIT: 'Full payment from credit',
    INVALID_MERCHANT: 'Gateway is invalid. Contact site support',
    LOGOUT_SUCCESSFULLY: 'Logout successful.',
    FOLDER_NOT_FOUND: 'Folder not found.',
    FILE_NOT_FOUND: 'File not found.',
    INVALID_FORMAT: 'File format not found.',
    FOLDER_HAS_CHILDREN: 'Folder contains subfolders or files.',
    FULLY_FROM_BALANCE: 'Payment from wallet',
    FULLY_FROM_CREDIT: 'Payment from credit',
    TYPE_PAY_1: 'Online payment',
    TYPE_PAY_2: 'In-person payment - POS',
    TYPE_PAY_3: 'Bank transfer',
    TYPE_PAY_4: 'Cash',
    TYPE_PAY_5: 'Cheque',
    SELECT_GATEWAY: 'Select payment gateway.',
  },
}

export default ku
